/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLocation: typeof import('@wwcattlewei/icons-vue')['AddLocation']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Plus: typeof import('@wwcattlewei/icons-vue')['Plus']
    TqAddLocation: typeof import('@wwcattlewei/icons-vue')['AddLocation']
    TqLus: typeof import('@wwcattlewei/icons-vue')['Lus']
    TqPlus: typeof import('@wwcattlewei/icons-vue')['Plus']
  }
}
