
console.log(323)
console.log(window)
window.demo = demo
const as = [
  {
    categories: "System",
    name: "加号",
    engliashName: "Plus",
    iconName: "Plus",
    type: "line",
  },
  {
    categories: "System",
    name: "减号",
    engliashName: "Minus",
    iconName: "Minus",
    type: "line",
  },
  {
    categories: "System",
    name: "CirclePlus",
    engliashName: "CirclePlus",
    iconName: "CirclePlus",
    type: "line",
  },
  {
    categories: "System",
    name: "搜索",
    engliashName: "Search",
    iconName: "Search",
    type: "line",
  },
  {
    categories: "System",
    name: "女性",
    engliashName: "Female",
    iconName: "Female",
    type: "line",
  },
  {
    categories: "System",
    name: "男性",
    engliashName: "Male",
    iconName: "Male",
    type: "line",
  },
  {
    categories: "System",
    name: "目标",
    engliashName: "Aim",
    iconName: "Aim",
    type: "line",
  },
  {
    categories: "System",
    name: "房子",
    engliashName: "House",
    iconName: "House",
    type: "line",
  },
  {
    categories: "System",
    name: "全屏",
    engliashName: "FullScreen",
    iconName: "FullScreen",
    type: "line",
  },
  {
    categories: "System",
    name: "正在加载",
    engliashName: "Loading",
    iconName: "Loading",
    type: "line",
  },
  {
    categories: "System",
    name: "链接",
    engliashName: "Link",
    iconName: "Link",
    type: "line",
  },
  {
    categories: "System",
    name: "服务",
    engliashName: "Service",
    iconName: "Service",
    type: "line",
  },
  {
    categories: "System",
    name: "指针",
    engliashName: "Pointer",
    iconName: "Pointer",
    type: "line",
  },
  {
    categories: "System",
    name: "星星",
    engliashName: "Star",
    iconName: "Star",
    type: "line",
  },
  {
    categories: "System",
    name: "通知",
    engliashName: "Notification",
    iconName: "Notification",
    type: "line",
  },
  {
    categories: "System",
    name: "连接",
    engliashName: "Connection",
    iconName: "Connection",
    type: "line",
  },
  {
    categories: "System",
    name: "ChatDotRound",
    engliashName: "ChatDotRound",
    iconName: "ChatDotRound",
    type: "line",
  },
  {
    categories: "System",
    name: "设置",
    engliashName: "Setting",
    iconName: "Setting",
    type: "line",
  },
  {
    categories: "System",
    name: "时钟",
    engliashName: "Clock",
    iconName: "Clock",
    type: "line",
  },
  {
    categories: "System",
    name: "位置",
    engliashName: "Position",
    iconName: "Position",
    type: "line",
  },
  {
    categories: "System",
    name: "折扣",
    engliashName: "Discount",
    iconName: "Discount",
    type: "line",
  },
  {
    categories: "System",
    name: "里程表",
    engliashName: "Odometer",
    iconName: "Odometer",
    type: "line",
  },
  {
    categories: "System",
    name: "聊天广场",
    engliashName: "ChatSquare",
    iconName: "ChatSquare",
    type: "line",
  },
  {
    categories: "System",
    name: "聊天回合”",
    engliashName: "ChatRound",
    iconName: "ChatRound",
    type: "line",
  },
  {
    categories: "System",
    name: "ChatLineRound",
    engliashName: "ChatLineRound",
    iconName: "ChatLineRound",
    type: "line",
  },
  {
    categories: "System",
    name: "ChatLineSquare",
    engliashName: "ChatLineSquare",
    iconName: "ChatLineSquare",
    type: "line",
  },
  {
    categories: "System",
    name: "ChatDotSquare",
    engliashName: "ChatDotSquare",
    iconName: "ChatDotSquare",
    type: "line",
  },
  {
    categories: "System",
    name: "视图",
    engliashName: "View",
    iconName: "View",
    type: "line",
  },
  {
    categories: "System",
    name: "隐藏",
    engliashName: "Hide",
    iconName: "Hide",
    type: "line",
  },
  {
    categories: "System",
    name: "解锁",
    engliashName: "Unlock",
    iconName: "Unlock",
    type: "line",
  },
  {
    categories: "System",
    name: "锁定",
    engliashName: "Lock",
    iconName: "Lock",
    type: "line",
  },
  {
    categories: "System",
    name: "刷新权限",
    engliashName: "RefreshRight",
    iconName: "RefreshRight",
    type: "line",
  },
  {
    categories: "System",
    name: "RefreshLeft",
    engliashName: "RefreshLeft",
    iconName: "RefreshLeft",
    type: "line",
  },
  {
    categories: "System",
    name: "刷新",
    engliashName: "Refresh",
    iconName: "Refresh",
    type: "line",
  },
  {
    categories: "System",
    name: "Bell",
    engliashName: "Bell",
    iconName: "Bell",
    type: "line",
  },
  {
    categories: "System",
    name: "静音通知",
    engliashName: "MuteNotification",
    iconName: "MuteNotification",
    type: "line",
  },
  {
    categories: "System",
    name: "用户",
    engliashName: "User",
    iconName: "User",
    type: "line",
  },
  {
    categories: "System",
    name: "检查",
    engliashName: "Check",
    iconName: "Check",
    type: "line",
  },
  {
    categories: "System",
    name: "CircleCheck",
    engliashName: "CircleCheck",
    iconName: "CircleCheck",
    type: "line",
  },
  {
    categories: "System",
    name: "警告",
    engliashName: "Warning",
    iconName: "Warning",
    type: "line",
  },
  {
    categories: "System",
    name: "CircleClose",
    engliashName: "CircleClose",
    iconName: "CircleClose",
    type: "line",
  },
  {
    categories: "System",
    name: "关闭",
    engliashName: "Close",
    iconName: "Close",
    type: "line",
  },
  {
    categories: "System",
    name: "饼图",
    engliashName: "PieChart",
    iconName: "PieChart",
    type: "line",
  },
  {
    categories: "System",
    name: "更多",
    engliashName: "More",
    iconName: "More",
    type: "line",
  },
  {
    categories: "System",
    name: "指南针",
    engliashName: "Compass",
    iconName: "Compass",
    type: "line",
  },
  {
    categories: "System",
    name: "过滤",
    engliashName: "Filter",
    iconName: "Filter",
    type: "line",
  },
  {
    categories: "System",
    name: "交换",
    engliashName: "Switch",
    iconName: "Switch",
    type: "line",
  },
  {
    categories: "System",
    name: "选择",
    engliashName: "Select",
    iconName: "Select",
    type: "line",
  },
  {
    categories: "System",
    name: "半选择",
    engliashName: "SemiSelect",
    iconName: "SemiSelect",
    type: "line",
  },
  {
    categories: "System",
    name: "CloseBold",
    engliashName: "CloseBold",
    iconName: "CloseBold",
    type: "line",
  },
  {
    categories: "System",
    name: "EditPen",
    engliashName: "EditPen",
    iconName: "EditPen",
    type: "line",
  },
  {
    categories: "System",
    name: "编辑",
    engliashName: "Edit",
    iconName: "Edit",
    type: "line",
  },
  {
    categories: "System",
    name: "消息",
    engliashName: "Message",
    iconName: "Message",
    type: "line",
  },
  {
    categories: "System",
    name: "消息框",
    engliashName: "MessageBox",
    iconName: "MessageBox",
    type: "line",
  },
  {
    categories: "System",
    name: "关闭",
    engliashName: "TurnOff",
    iconName: "TurnOff",
    type: "line",
  },
  {
    categories: "System",
    name: "完成",
    engliashName: "Finished",
    iconName: "Finished",
    type: "line",
  },
  {
    categories: "System",
    name: "删除",
    engliashName: "Delete",
    iconName: "Delete",
    type: "line",
  },
  {
    categories: "System",
    name: "裁剪",
    engliashName: "Crop",
    iconName: "Crop",
    type: "line",
  },
  {
    categories: "System",
    name: "切换按钮",
    engliashName: "SwitchButton",
    iconName: "SwitchButton",
    type: "line",
  },
  {
    categories: "System",
    name: "操作",
    engliashName: "Operation",
    iconName: "Operation",
    type: "line",
  },
  {
    categories: "System",
    name: "打开",
    engliashName: "Open",
    iconName: "Open",
    type: "line",
  },
  {
    categories: "System",
    name: "移动",
    engliashName: "Remove",
    iconName: "Remove",
    type: "line",
  },
  {
    categories: "System",
    name: "缩小",
    engliashName: "ZoomOut",
    iconName: "ZoomOut",
    type: "line",
  },
  {
    categories: "System",
    name: "放大",
    engliashName: "ZoomIn",
    iconName: "ZoomIn",
    type: "line",
  },
  {
    categories: "System",
    name: "信息填充",
    engliashName: "InfoFilled",
    iconName: "InfoFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "CircleCheckFilled",
    engliashName: "CircleCheckFilled",
    iconName: "CircleCheckFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "成功填充",
    engliashName: "SuccessFilled",
    iconName: "SuccessFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "WarningFilled",
    engliashName: "WarningFilled",
    iconName: "WarningFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "CircleCloseFilled",
    engliashName: "CircleCloseFilled",
    iconName: "CircleCloseFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "QuestionFilled",
    engliashName: "QuestionFilled",
    iconName: "QuestionFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "WarnTriangleFilled",
    engliashName: "WarnTriangleFilled",
    iconName: "WarnTriangleFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "用户",
    engliashName: "UserFilled",
    iconName: "UserFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "MoreFilled",
    engliashName: "MoreFilled",
    iconName: "MoreFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "工具",
    engliashName: "Tools",
    iconName: "Tools",
    type: "line",
  },
  {
    categories: "System",
    name: "主页",
    engliashName: "HomeFilled",
    iconName: "HomeFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "菜单",
    engliashName: "Menu",
    iconName: "Menu",
    type: "line",
  },
  {
    categories: "System",
    name: "下载",
    engliashName: "UploadFilled",
    iconName: "UploadFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "头像",
    engliashName: "Avatar",
    iconName: "Avatar",
    type: "line",
  },
  {
    categories: "System",
    name: "帮助",
    engliashName: "HelpFilled",
    iconName: "HelpFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "分享",
    engliashName: "Share",
    iconName: "Share",
    type: "line",
  },
  {
    categories: "System",
    name: "星星",
    engliashName: "StarFilled",
    iconName: "StarFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "注释",
    engliashName: "Comment",
    iconName: "Comment",
    type: "line",
  },
  {
    categories: "System",
    name: "直方图",
    engliashName: "Histogram",
    iconName: "Histogram",
    type: "line",
  },
  {
    categories: "System",
    name: "网格",
    engliashName: "Grid",
    iconName: "Grid",
    type: "line",
  },
  {
    categories: "System",
    name: "促销",
    engliashName: "Promotion",
    iconName: "Promotion",
    type: "line",
  },
  {
    categories: "System",
    name: "删除",
    engliashName: "DeleteFilled",
    iconName: "DeleteFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "移动",
    engliashName: "RemoveFilled",
    iconName: "RemoveFilled",
    type: "line",
  },
  {
    categories: "System",
    name: "CirclePlusFilled",
    engliashName: "CirclePlusFilled",
    iconName: "CirclePlusFilled",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向左箭头",
    engliashName: "ArrowLeft",
    iconName: "ArrowLeft",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向上箭头",
    engliashName: "ArrowUp",
    iconName: "ArrowUp",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向右箭头",
    engliashName: "ArrowRight",
    iconName: "ArrowRight",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向下箭头",
    engliashName: "ArrowDown",
    iconName: "ArrowDown",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向左箭头",
    engliashName: "ArrowLeftBold",
    iconName: "ArrowLeftBold",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向下箭头",
    engliashName: "ArrowUpBold",
    iconName: "ArrowUpBold",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向右箭头",
    engliashName: "ArrowRightBold",
    iconName: "ArrowRightBold",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向下箭头",
    engliashName: "ArrowDownBold",
    iconName: "ArrowDownBold",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向右箭头",
    engliashName: "DArrowRight",
    iconName: "DArrowRight",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "向左箭头",
    engliashName: "DArrowLeft",
    iconName: "DArrowLeft",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "下载",
    engliashName: "Download",
    iconName: "Download",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "上传",
    engliashName: "Upload",
    iconName: "Upload",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "顶部",
    engliashName: "Top",
    iconName: "Top",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "底部",
    engliashName: "Bottom",
    iconName: "Bottom",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "返回",
    engliashName: "Back",
    iconName: "Back",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "右侧",
    engliashName: "Right",
    iconName: "Right",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "右上角",
    engliashName: "TopRight",
    iconName: "TopRight",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "左上角",
    engliashName: "TopLeft",
    iconName: "TopLeft",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "底部右侧",
    engliashName: "BottomRight",
    iconName: "BottomRight",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "底部左侧",
    engliashName: "BottomLeft",
    iconName: "BottomLeft",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "排序",
    engliashName: "Sort",
    iconName: "Sort",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "SortUp",
    engliashName: "SortUp",
    iconName: "SortUp",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "排序",
    engliashName: "SortDown",
    iconName: "SortDown",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "排行榜",
    engliashName: "Rank",
    iconName: "Rank",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "CaretLeft",
    engliashName: "CaretLeft",
    iconName: "CaretLeft",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "CaretTop",
    engliashName: "CaretTop",
    iconName: "CaretTop",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "CaretRight",
    engliashName: "CaretRight",
    iconName: "CaretRight",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "CaretBottom",
    engliashName: "CaretBottom",
    iconName: "CaretBottom",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "DCaret",
    engliashName: "DCaret",
    iconName: "DCaret",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "展开",
    engliashName: "Expand",
    iconName: "Expand",
    type: "line",
  },
  {
    categories: "Arrow",
    name: "折叠",
    engliashName: "Fold",
    iconName: "Fold",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档添加",
    engliashName: "DocumentAdd",
    iconName: "DocumentAdd",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档",
    engliashName: "Document",
    iconName: "Document",
    type: "line",
  },
  {
    categories: "Document",
    name: "笔记本",
    engliashName: "Notebook",
    iconName: "Notebook",
    type: "line",
  },
  {
    categories: "Document",
    name: "门票",
    engliashName: "Tickets",
    iconName: "Tickets",
    type: "line",
  },
  {
    categories: "Document",
    name: "备注",
    engliashName: "Memo",
    iconName: "Memo",
    type: "line",
  },
  {
    categories: "Document",
    name: "集合",
    engliashName: "Collection",
    iconName: "Collection",
    type: "line",
  },
  {
    categories: "Document",
    name: "明信片",
    engliashName: "Postcard",
    iconName: "Postcard",
    type: "line",
  },
  {
    categories: "Document",
    name: "缩放原始",
    engliashName: "ScaleToOriginal",
    iconName: "ScaleToOriginal",
    type: "line",
  },
  {
    categories: "Document",
    name: "设置",
    engliashName: "SetUp",
    iconName: "SetUp",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档删除",
    engliashName: "DocumentDelete",
    iconName: "DocumentDelete",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档检查",
    engliashName: "DocumentChecked",
    iconName: "DocumentChecked",
    type: "line",
  },
  {
    categories: "Document",
    name: "数据板",
    engliashName: "DataBoard",
    iconName: "DataBoard",
    type: "line",
  },
  {
    categories: "Document",
    name: "数据分析",
    engliashName: "DataAnalysis",
    iconName: "DataAnalysis",
    type: "line",
  },
  {
    categories: "Document",
    name: "复制文档",
    engliashName: "CopyDocument",
    iconName: "CopyDocument",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件检查",
    engliashName: "FolderChecked",
    iconName: "FolderChecked",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件",
    engliashName: "Files",
    iconName: "Files",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件夹",
    engliashName: "Folder",
    iconName: "Folder",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件夹删除",
    engliashName: "FolderDelete",
    iconName: "FolderDelete",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件夹移除",
    engliashName: "FolderRemove",
    iconName: "FolderRemove",
    type: "line",
  },
  {
    categories: "Document",
    name: "打开文件夹",
    engliashName: "FolderOpened",
    iconName: "FolderOpened",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档复制",
    engliashName: "DocumentCopy",
    iconName: "DocumentCopy",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档移除",
    engliashName: "DocumentRemove",
    iconName: "DocumentRemove",
    type: "line",
  },
  {
    categories: "Document",
    name: "文件夹添加",
    engliashName: "FolderAdd",
    iconName: "FolderAdd",
    type: "line",
  },
  {
    categories: "Document",
    name: "急救包",
    engliashName: "FirstAidKit",
    iconName: "FirstAidKit",
    type: "line",
  },
  {
    categories: "Document",
    name: "阅读",
    engliashName: "Reading",
    iconName: "Reading",
    type: "line",
  },
  {
    categories: "Document",
    name: "文档线",
    engliashName: "DataLine",
    iconName: "DataLine",
    type: "line",
  },
  {
    categories: "Document",
    name: "管理",
    engliashName: "Management",
    iconName: "Management",
    type: "line",
  },
  {
    categories: "Document",
    name: "选中",
    engliashName: "Checked",
    iconName: "Checked",
    type: "line",
  },
  {
    categories: "Document",
    name: "票证",
    engliashName: "Ticket",
    iconName: "Ticket",
    type: "line",
  },
  {
    categories: "Document",
    name: "失败",
    engliashName: "Failed",
    iconName: "Failed",
    type: "line",
  },
  {
    categories: "Document",
    name: "趋势图",
    engliashName: "TrendCharts",
    iconName: "TrendCharts",
    type: "line",
  },
  {
    categories: "Document",
    name: "列表",
    engliashName: "List",
    iconName: "List",
    type: "line",
  },
  {
    categories: "Media",
    name: "媒体",
    engliashName: "Microphone",
    iconName: "Microphone",
    type: "line",
  },
  {
    categories: "Media",
    name: "静音",
    engliashName: "Mute",
    iconName: "Mute",
    type: "line",
  },
  {
    categories: "Media",
    name: "麦克风",
    engliashName: "Mic",
    iconName: "Mic",
    type: "line",
  },
  {
    categories: "Media",
    name: "视频暂停",
    engliashName: "VideoPause",
    iconName: "VideoPause",
    type: "line",
  },
  {
    categories: "Media",
    name: "VideoCamera",
    engliashName: "VideoCamera",
    iconName: "VideoCamera",
    type: "line",
  },
  {
    categories: "Media",
    name: "VideoPlay",
    engliashName: "VideoPlay",
    iconName: "VideoPlay",
    type: "line",
  },
  {
    categories: "Media",
    name: "Headset",
    engliashName: "Headset",
    iconName: "Headset",
    type: "line",
  },
  {
    categories: "Media",
    name: "Monitor",
    engliashName: "Monitor",
    iconName: "Monitor",
    type: "line",
  },
  {
    categories: "Media",
    name: "Film",
    engliashName: "Film",
    iconName: "Film",
    type: "line",
  },
  {
    categories: "Media",
    name: "Camera",
    engliashName: "Camera",
    iconName: "Camera",
    type: "line",
  },
  {
    categories: "Media",
    name: "Picture",
    engliashName: "Picture",
    iconName: "Picture",
    type: "line",
  },
  {
    categories: "Media",
    name: "PictureRounded",
    engliashName: "PictureRounded",
    iconName: "PictureRounded",
    type: "line",
  },
  {
    categories: "Media",
    name: "Iphone",
    engliashName: "Iphone",
    iconName: "Iphone",
    type: "line",
  },
  {
    categories: "Media",
    name: "Cellphone",
    engliashName: "Cellphone",
    iconName: "Cellphone",
    type: "line",
  },
  {
    categories: "Media",
    name: "VideoCameraFilled",
    engliashName: "VideoCameraFilled",
    iconName: "VideoCameraFilled",
    type: "line",
  },
  {
    categories: "Media",
    name: "PictureFilled",
    engliashName: "PictureFilled",
    iconName: "PictureFilled",
    type: "line",
  },
  {
    categories: "Media",
    name: "Platform",
    engliashName: "Platform",
    iconName: "Platform",
    type: "line",
  },
  {
    categories: "Media",
    name: "CameraFilled",
    engliashName: "CameraFilled",
    iconName: "CameraFilled",
    type: "line",
  },
  {
    categories: "Media",
    name: "BellFilled",
    engliashName: "BellFilled",
    iconName: "BellFilled",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Location",
    engliashName: "Location",
    iconName: "Location",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "LocationInformation",
    engliashName: "LocationInformation",
    iconName: "LocationInformation",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "DeleteLocation",
    engliashName: "DeleteLocation",
    iconName: "DeleteLocation",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Coordinate",
    engliashName: "Coordinate",
    iconName: "Coordinate",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Bicycle",
    engliashName: "Bicycle",
    iconName: "Bicycle",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "OfficeBuilding",
    engliashName: "OfficeBuilding",
    iconName: "OfficeBuilding",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "School",
    engliashName: "School",
    iconName: "School",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Guide",
    engliashName: "Guide",
    iconName: "Guide",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "AddLocation",
    engliashName: "AddLocation",
    iconName: "AddLocation",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "MapLocation",
    engliashName: "MapLocation",
    iconName: "MapLocation",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Place",
    engliashName: "Place",
    iconName: "Place",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "LocationFilled",
    engliashName: "LocationFilled",
    iconName: "LocationFilled",
    type: "line",
  },
  {
    categories: "Traffic",
    name: "Van",
    engliashName: "Van",
    iconName: "Van",
    type: "line",
  },
  {
    categories: "Food",
    name: "Watermelon",
    engliashName: "Watermelon",
    iconName: "Watermelon",
    type: "line",
  },
  {
    categories: "Food",
    name: "Pear",
    engliashName: "Pear",
    iconName: "Pear",
    type: "line",
  },
  {
    categories: "Food",
    name: "NoSmoking",
    engliashName: "NoSmoking",
    iconName: "NoSmoking",
    type: "line",
  },
  {
    categories: "Food",
    name: "Smoking",
    engliashName: "Smoking",
    iconName: "Smoking",
    type: "line",
  },
  {
    categories: "Food",
    name: "Mug",
    engliashName: "Mug",
    iconName: "Mug",
    type: "line",
  },
  {
    categories: "Food",
    name: "GobletSquareFull",
    engliashName: "GobletSquareFull",
    iconName: "GobletSquareFull",
    type: "line",
  },
  {
    categories: "Food",
    name: "GobletFull",
    engliashName: "GobletFull",
    iconName: "GobletFull",
    type: "line",
  },
  {
    categories: "Food",
    name: "KnifeFork",
    engliashName: "KnifeFork",
    iconName: "KnifeFork",
    type: "line",
  },
  {
    categories: "Food",
    name: "Sugar",
    engliashName: "Sugar",
    iconName: "Sugar",
    type: "line",
  },
  {
    categories: "Food",
    name: "Bowl",
    engliashName: "Bowl",
    iconName: "Bowl",
    type: "line",
  },
  {
    categories: "Food",
    name: "MilkTea",
    engliashName: "MilkTea",
    iconName: "MilkTea",
    type: "line",
  },
  {
    categories: "Food",
    name: "Lollipop",
    engliashName: "Lollipop",
    iconName: "Lollipop",
    type: "line",
  },
  {
    categories: "Food",
    name: "Coffee",
    engliashName: "Coffee",
    iconName: "Coffee",
    type: "line",
  },
  {
    categories: "Food",
    name: "Chicken",
    engliashName: "Chicken",
    iconName: "Chicken",
    type: "line",
  },
  {
    categories: "Food",
    name: "Dish",
    engliashName: "Dish",
    iconName: "Dish",
    type: "line",
  },
  {
    categories: "Food",
    name: "IceTea",
    engliashName: "IceTea",
    iconName: "IceTea",
    type: "line",
  },
  {
    categories: "Food",
    name: "ColdDrink",
    engliashName: "ColdDrink",
    iconName: "ColdDrink",
    type: "line",
  },
  {
    categories: "Food",
    name: "CoffeeCup",
    engliashName: "CoffeeCup",
    iconName: "CoffeeCup",
    type: "line",
  },
  {
    categories: "Food",
    name: "DishDot",
    engliashName: "DishDot",
    iconName: "DishDot",
    type: "line",
  },
  {
    categories: "Food",
    name: "IceDrink",
    engliashName: "IceDrink",
    iconName: "IceDrink",
    type: "line",
  },
  {
    categories: "Food",
    name: "IceCream",
    engliashName: "IceCream",
    iconName: "IceCream",
    type: "line",
  },
  {
    categories: "Food",
    name: "Dessert",
    engliashName: "Dessert",
    iconName: "Dessert",
    type: "line",
  },
  {
    categories: "Food",
    name: "IceCreamSquare",
    engliashName: "IceCreamSquare",
    iconName: "IceCreamSquare",
    type: "line",
  },
  {
    categories: "Food",
    name: "ForkSpoon",
    engliashName: "ForkSpoon",
    iconName: "ForkSpoon",
    type: "line",
  },
  {
    categories: "Food",
    name: "IceCreamRound",
    engliashName: "IceCreamRound",
    iconName: "IceCreamRound",
    type: "line",
  },
  {
    categories: "Food",
    name: "Food",
    engliashName: "Food",
    iconName: "Food",
    type: "line",
  },
  {
    categories: "Food",
    name: "HotWater",
    engliashName: "HotWater",
    iconName: "HotWater",
    type: "line",
  },
  {
    categories: "Food",
    name: "Grape",
    engliashName: "Grape",
    iconName: "Grape",
    type: "line",
  },
  {
    categories: "Food",
    name: "Fries",
    engliashName: "Fries",
    iconName: "Fries",
    type: "line",
  },
  {
    categories: "Food",
    name: "Apple",
    engliashName: "Apple",
    iconName: "Apple",
    type: "line",
  },
  {
    categories: "Food",
    name: "Burger",
    engliashName: "Burger",
    iconName: "Burger",
    type: "line",
  },
  {
    categories: "Food",
    name: "Goblet",
    engliashName: "Goblet",
    iconName: "Goblet",
    type: "line",
  },
  {
    categories: "Food",
    name: "GobletSquare",
    engliashName: "GobletSquare",
    iconName: "GobletSquare",
    type: "line",
  },
  {
    categories: "Food",
    name: "Orange",
    engliashName: "Orange",
    iconName: "Orange",
    type: "line",
  },
  {
    categories: "Food",
    name: "Cherry",
    engliashName: "Cherry",
    iconName: "Cherry",
    type: "line",
  },
  {
    categories: "Items",
    name: "Printer",
    engliashName: "Printer",
    iconName: "Printer",
    type: "line",
  },
  {
    categories: "Items",
    name: "Calendar",
    engliashName: "Calendar",
    iconName: "Calendar",
    type: "line",
  },
  {
    categories: "Items",
    name: "CreditCard",
    engliashName: "CreditCard",
    iconName: "CreditCard",
    type: "line",
  },
  {
    categories: "Items",
    name: "Box",
    engliashName: "Box",
    iconName: "Box",
    type: "line",
  },
  {
    categories: "Items",
    name: "Money",
    engliashName: "Money",
    iconName: "Money",
    type: "line",
  },
  {
    categories: "Items",
    name: "Refrigerator",
    engliashName: "Refrigerator",
    iconName: "Refrigerator",
    type: "line",
  },
  {
    categories: "Items",
    name: "Cpu",
    engliashName: "Cpu",
    iconName: "Cpu",
    type: "line",
  },
  {
    categories: "Items",
    name: "Football",
    engliashName: "Football",
    iconName: "Football",
    type: "line",
  },
  {
    categories: "Items",
    name: "Brush",
    engliashName: "Brush",
    iconName: "Brush",
    type: "line",
  },
  {
    categories: "Items",
    name: "Suitcase",
    engliashName: "Suitcase",
    iconName: "Suitcase",
    type: "line",
  },
  {
    categories: "Items",
    name: "SuitcaseLine",
    engliashName: "SuitcaseLine",
    iconName: "SuitcaseLine",
    type: "line",
  },
  {
    categories: "Items",
    name: "Umbrella",
    engliashName: "Umbrella",
    iconName: "Umbrella",
    type: "line",
  },
  {
    categories: "Items",
    name: "AlarmClock",
    engliashName: "AlarmClock",
    iconName: "AlarmClock",
    type: "line",
  },
  {
    categories: "Items",
    name: "Medal",
    engliashName: "Medal",
    iconName: "Medal",
    type: "line",
  },
  {
    categories: "Items",
    name: "GoldMedal",
    engliashName: "GoldMedal",
    iconName: "GoldMedal",
    type: "line",
  },
  {
    categories: "Items",
    name: "Present",
    engliashName: "Present",
    iconName: "Present",
    type: "line",
  },
  {
    categories: "Items",
    name: "Mouse",
    engliashName: "Mouse",
    iconName: "Mouse",
    type: "line",
  },
  {
    categories: "Items",
    name: "Watch",
    engliashName: "Watch",
    iconName: "Watch",
    type: "line",
  },
  {
    categories: "Items",
    name: "QuartzWatch",
    engliashName: "QuartzWatch",
    iconName: "QuartzWatch",
    type: "line",
  },
  {
    categories: "Items",
    name: "Magnet",
    engliashName: "Magnet",
    iconName: "Magnet",
    type: "line",
  },
  {
    categories: "Items",
    name: "Help",
    engliashName: "Help",
    iconName: "Help",
    type: "line",
  },
  {
    categories: "Items",
    name: "Soccer",
    engliashName: "Soccer",
    iconName: "Soccer",
    type: "line",
  },
  {
    categories: "Items",
    name: "ToiletPaper",
    engliashName: "ToiletPaper",
    iconName: "ToiletPaper",
    type: "line",
  },
  {
    categories: "Items",
    name: "ReadingLamp",
    engliashName: "ReadingLamp",
    iconName: "ReadingLamp",
    type: "line",
  },
  {
    categories: "Items",
    name: "Paperclip",
    engliashName: "Paperclip",
    iconName: "Paperclip",
    type: "line",
  },
  {
    categories: "Items",
    name: "MagicStick",
    engliashName: "MagicStick",
    iconName: "MagicStick",
    type: "line",
  },
  {
    categories: "Items",
    name: "Basketball",
    engliashName: "Basketball",
    iconName: "Basketball",
    type: "line",
  },
  {
    categories: "Items",
    name: "Baseball",
    engliashName: "Baseball",
    iconName: "Baseball",
    type: "line",
  },
  {
    categories: "Items",
    name: "Coin",
    engliashName: "Coin",
    iconName: "Coin",
    type: "line",
  },
  {
    categories: "Items",
    name: "Goods",
    engliashName: "Goods",
    iconName: "Goods",
    type: "line",
  },
  {
    categories: "Items",
    name: "Sell",
    engliashName: "Sell",
    iconName: "Sell",
    type: "line",
  },
  {
    categories: "Items",
    name: "SoldOut",
    engliashName: "SoldOut",
    iconName: "SoldOut",
    type: "line",
  },
  {
    categories: "Items",
    name: "Key",
    engliashName: "Key",
    iconName: "Key",
    type: "line",
  },
  {
    categories: "Items",
    name: "ShoppingCart",
    engliashName: "ShoppingCart",
    iconName: "ShoppingCart",
    type: "line",
  },
  {
    categories: "Items",
    name: "ShoppingCartFull",
    engliashName: "ShoppingCartFull",
    iconName: "ShoppingCartFull",
    type: "line",
  },
  {
    categories: "Items",
    name: "ShoppingTrolley",
    engliashName: "ShoppingTrolley",
    iconName: "ShoppingTrolley",
    type: "line",
  },
  {
    categories: "Items",
    name: "Phone",
    engliashName: "Phone",
    iconName: "Phone",
    type: "line",
  },
  {
    categories: "Items",
    name: "Scissor",
    engliashName: "Scissor",
    iconName: "Scissor",
    type: "line",
  },
  {
    categories: "Items",
    name: "Handbag",
    engliashName: "Handbag",
    iconName: "Handbag",
    type: "line",
  },
  {
    categories: "Items",
    name: "ShoppingBag",
    engliashName: "ShoppingBag",
    iconName: "ShoppingBag",
    type: "line",
  },
  {
    categories: "Items",
    name: "Trophy",
    engliashName: "Trophy",
    iconName: "Trophy",
    type: "line",
  },
  {
    categories: "Items",
    name: "TrophyBase",
    engliashName: "TrophyBase",
    iconName: "TrophyBase",
    type: "line",
  },
  {
    categories: "Items",
    name: "Stopwatch",
    engliashName: "Stopwatch",
    iconName: "Stopwatch",
    type: "line",
  },
  {
    categories: "Items",
    name: "Timer",
    engliashName: "Timer",
    iconName: "Timer",
    type: "line",
  },
  {
    categories: "Items",
    name: "CollectionTag",
    engliashName: "CollectionTag",
    iconName: "CollectionTag",
    type: "line",
  },
  {
    categories: "Items",
    name: "Discount",
    engliashName: "Discount",
    iconName: "Discount",
    type: "line",
  },
  {
    categories: "Items",
    name: "TakeawayBox",
    engliashName: "TakeawayBox",
    iconName: "TakeawayBox",
    type: "line",
  },
  {
    categories: "Items",
    name: "PriceTag",
    engliashName: "PriceTag",
    iconName: "PriceTag",
    type: "line",
  },
  {
    categories: "Items",
    name: "Wallet",
    engliashName: "Wallet",
    iconName: "Wallet",
    type: "line",
  },
  {
    categories: "Items",
    name: "Opportunity",
    engliashName: "Opportunity",
    iconName: "Opportunity",
    type: "line",
  },
  {
    categories: "Items",
    name: "PhoneFilled",
    engliashName: "PhoneFilled",
    iconName: "PhoneFilled",
    type: "line",
  },
  {
    categories: "Items",
    name: "WalletFilled",
    engliashName: "WalletFilled",
    iconName: "WalletFilled",
    type: "line",
  },
  {
    categories: "Items",
    name: "GoodsFilled",
    engliashName: "GoodsFilled",
    iconName: "GoodsFilled",
    type: "line",
  },
  {
    categories: "Items",
    name: "Flag",
    engliashName: "Flag",
    iconName: "Flag",
    type: "line",
  },
  {
    categories: "Items",
    name: "BrushFilled",
    engliashName: "BrushFilled",
    iconName: "BrushFilled",
    type: "line",
  },
  {
    categories: "Items",
    name: "Briefcase",
    engliashName: "Briefcase",
    iconName: "Briefcase",
    type: "line",
  },
  {
    categories: "Items",
    name: "Stamp",
    engliashName: "Stamp",
    iconName: "Stamp",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Sunrise",
    engliashName: "Sunrise",
    iconName: "Sunrise",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Sunny",
    engliashName: "Sunny",
    iconName: "Sunny",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Ship",
    engliashName: "Ship",
    iconName: "Ship",
    type: "line",
  },
  {
    categories: "Weather",
    name: "MostlyCloudy",
    engliashName: "MostlyCloudy",
    iconName: "MostlyCloudy",
    type: "line",
  },
  {
    categories: "Weather",
    name: "PartlyCloudy",
    engliashName: "PartlyCloudy",
    iconName: "PartlyCloudy",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Sunset",
    engliashName: "Sunset",
    iconName: "Sunset",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Sunrise",
    engliashName: "Sunrise",
    iconName: "Sunrise",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Drizzling",
    engliashName: "Drizzling",
    iconName: "Drizzling",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Pouring",
    engliashName: "Pouring",
    iconName: "Pouring",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Cloudy",
    engliashName: "Cloudy",
    iconName: "Cloudy",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Moon",
    engliashName: "Moon",
    iconName: "Moon",
    type: "line",
  },
  {
    categories: "Weather",
    name: "MoonNight",
    engliashName: "MoonNight",
    iconName: "MoonNight",
    type: "line",
  },
  {
    categories: "Weather",
    name: "Lightning",
    engliashName: "Lightning",
    iconName: "Lightning",
    type: "line",
  },
]
